name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Add permissions to build script
        run: chmod +x ./build.sh

      - name: Build archives
        run: ./build.sh

      - name: Configure git name and email
        run: |
          git config user.name "Builder"
          git config user.email "tigerros.gh@gmail.com"

      - name: Add dist
        run: git add --force dist/*

      - name: Commit changed files
        run: git commit -m "Generate chromium.zip from commit ${{ github.event.head_commit.url }}"

      - name: Push code
        run: git push